[workspace]
members = [
	"client",
	"server",
]

[profile.release]
lto = true
codegen-units = 1

[workspace.metadata.nix]
systems = ["x86_64-linux"]
buildInputs = ["openssl"]
nativeBuildInputs = ["pkg-config"]
