[package]
name = "server"
version = "0.4.2"
authors = ["Songtronix <contact@songtronix.com>"]
edition = "2018"
publish = false

[package.metadata.nix]
build = true
app = true
library = true

[dependencies]
tokio-util = { version = "0.6.6", features = ["codec"] }
tokio = "1.5.0"
# logging
tracing = { version = "0.1.25", features = ["log"] }
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.17"
# Webserver
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "dd0c036" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "dd0c036", features = ["json"] }
# Networking
reqwest = "0.11.3"
# Serialising/Deserialising
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
# Database
sqlx = { version = "0.5.2", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }
# Error handling
thiserror = "1.0.24"
# other
chrono = { version = "0.4.19", features = ["serde"] }
lazy_static = "1.4.0"
prometheus = "0.12.0"
futures = "0.3.14"
dotenv = "0.15.0"
bytes = "1.0.1"
md5 = "0.7.0"
